### ISSUE TITLE
Implement Details Sidebar (Plants, Restaurant)

### ISSUE THREAD

**Issue by Yannic-reust** [Yannic-reust/polyslope#6]
- [ ] add Title and Text
- [ ] add closed state Element (e.g Anlagen) 
- [ ] add open state Element
- [ ] smooth dropdown animation
- [ ] preparation, dynamic color change status

**Comment by DerBeton** [comment]
Maybe you could add the following requirements:

- Change icon on open/close state
- Make camera icon optional (not every plant/restaurant is focusable)
